- hosts: localhost
  tasks:
    - name: Ensure Docker Swarm is initialized
      community.docker.docker_swarm:
        state: present

    - name: Create overlay network
      community.docker.docker_network:
        name: wazuh-net
        driver: overlay
        state: present

    - name: Deploy Wazuh stack
      community.docker.docker_stack:
        state: present
        name: wazuh
        compose:
          - "{{ playbook_dir }}/../../stack/wazuh-stack.yml"
