- name: Deploy Wazuh Stack on Docker Swarm
  hosts: swarm_nodes
  become: yes
  tasks:
    - name: Ensure Docker Swarm is initialized
      community.docker.docker_swarm:
        state: present

    - name: Create overlay network
      community.docker.docker_network:
        name: wazuh-net
        driver: overlay
        state: present

    - name: Deploy Wazuh Stack
      community.docker.docker_stack:
        name: wazuh
        state: present
        compose:
           - "/home/heelioos/mini-soc/docker/compose/wazuh-stack.yml"
