name: Mini-SOC CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build Wazuh images
        run: docker compose -f stack/wazuh-stack.yml build

      - name: Scan with Trivy
        run: trivy image wazuh/wazuh-manager:4.10.0 --exit-code 1 --severity CRITICAL,HIGH

      - name: Ansible Deploy
        run: ansible-playbook ansible/playbooks/deploy.yml
