name: Build & Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-scan:
    runs-on: self-hosted   # your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker images
        run: |
          docker build -t mini-soc/wazuh-manager:latest ./docker/wazuh-manager
          docker build -t mini-soc/wazuh-kibana:latest ./docker/wazuh-kibana

      - name: Scan images with Trivy
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH mini-soc/wazuh-manager:latest
          trivy image --exit-code 1 --severity CRITICAL,HIGH mini-soc/wazuh-kibana:latest

