name: Selenium Tests

on:
  workflow_run:
    workflows: ["Build & Scan"]
    types:
      - completed

jobs:
  selenium-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Selenium tests
        run: |
          pip install -r requirements.txt
          pytest tests/selenium

